### ISSUE TITLE
Support for negative numbers in parenthesis

### ISSUE THREAD

**Issue by cmllmrnn** [nielstron/quantulum3#103]
**Is your feature request related to a problem? Please describe.**
To display negative currencies or other units, some users prefer the format ($99.99) instead of -$99.99 especially in accounting. 

**Describe the solution you'd like**
Considering numbers inside parenthesis as negative will be very helpful in all units of measurement.

**Comment by nielstron** [comment]
> Considering numbers inside parenthesis as negative will be very helpful in all units of measurement.

Especially for **all units of measurement** I consider this behavior undesirable. Image a sentence in written text like "there were many (4) cars", definitely not referring to a negative number 

> some users prefer the format ($99.99) instead of -$99.99 

This is very well implementable, placed in the method [`build_quantity`](https://github.com/nielstron/quantulum3/blob/e43796e117007e4cad0e9282d16c31fd368fd237/quantulum3/_lang/en_US/parser.py#L125) where dozens of special cases are handled.
