### ISSUE TITLE
Getting FileNotFoundError while running parser.parse('5.8 mass') in Python 3.6 and python3.5 

### ISSUE THREAD

**Issue by rajeshkumargp** [nielstron/quantulum3#122]
**Describe the bug**
Getting FileNotFoundError while running parser.parse('5.8 mass') in Python 3.6 and python3.5 

**To Reproduce**
from quantulum3 import parser
quants = parser.parse('5.8 mass')

**Error**

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/quantulum3/_lang/en_US/train'

**Additional information:**
 - Python Version: 3.5,3.7
 - OS: [e.g. iOS] Ubuntu 16.04

**Comment by nielstron** [comment]
Please post the full error so I can see where (in which line) the error is created :)

**Comment by nielstron** [comment]
Should be fixed by #123. Please reopen if the problem persists after downloading the new version :)

**Comment by rajeshkumargp** [comment]
Issue resolved now
Thanks for the quick fix.
