### ISSUE TITLE
Windows/OSX support (AttributeError: module 'os' has no attribute 'sched_getaffinity')

### ISSUE THREAD

**Issue by radu-gheorghe** [nielstron/quantulum3#124]
**Describe the bug**
It looks like quantulum3 doesn't work on OSX or Windows

**To Reproduce**
1. Install scikit-learn (brings in numpy and scipy)
2. Install quantulum3
3. Do `from quantulum3 import parser`

Here's what I get on Windows:
```Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from quantulum3 import parser
C:\System\Python\Python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\System\Python\Python37\lib\site-packages\quantulum3\parser.py", line 17, in <module>
    from . import disambiguate as dis
  File "C:\System\Python\Python37\lib\site-packages\quantulum3\disambiguate.py", line 7, in <module>
    from . import classifier as clf
  File "C:\System\Python\Python37\lib\site-packages\quantulum3\classifier.py", line 120, in <module>
    n_jobs=len(os.sched_getaffinity(0))):
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```

**Additional information:**
 - Python Version: 3.7.3
 - Classifier activated/ sklearn installed: yes
 - OS: Windows Server 2019 Standard
 - Version: 0.7.1

**Additional context**
AFAIK, `sched_getaffinity` is only supported for Linux. On Linux it runs fine (aside from the warning on joblib - which seems to be brought automatically when installing scikit-learn). Maybe the AttributeError can be catched, so that `os.cpu_count()` can be used instead? I could submit a PR if that helps.

**Comment by nielstron** [comment]
Sure, the problem is that sched_getaffinity does not work on all systems (sometimes not even Unix). The proposal of catching the error seems like a good idea, I will definitely look into that.
