### ISSUE TITLE
How to get the unit short form

### ISSUE THREAD

**Issue by ManivannanIkomet** [nielstron/quantulum3#142]
text = 50 ± 60 mg×l–1
```
Output :
unt = parser.parse('50 ± 60 mg×l–1')
print(unt[0].unit.name)
milligram per litre
```
Expected:
How to get the only short form
```mg×l–1```

**Comment by ManivannanIkomet** [comment]
hi @nielstron 
Please help me

**Comment by nielstron** [comment]
please have a look at the "surface" attribute of the quantity and unit classes. They should be set appropriately in your result :)

**Comment by ManivannanIkomet** [comment]
I get only mg×l–1 from '50 ± 60 mg×l–1'
But the surface return full string
