### ISSUE TITLE
How to find the proper litre value

### ISSUE THREAD

**Issue by ManivannanIkomet** [nielstron/quantulum3#143]
Hi @nielstron,

How to find the entity as unit not volumn.
I need get the output as litre not centimeter or meter
How can i find?

1 milliliter = | 1 cubic centimeter
-- | --
1 kiloliter = | 1 cubic meter
```
parser.parse('5 ml')
[Quantity(5, "Unit(name="cubic centimetre", entity=Entity("volume"), uri=Cubic_centimetre)")]

parser.parse('5 kl')
[Quantity(5, "Unit(name="cubic metre", entity=Entity("volume"), uri=Cubic_metre)")]
``` 

and

Wrong prediction:
centilitre(cl) predict as dimensionless
```
parser.parse('1 cl')
[Quantity(1, "Unit(name="dimensionless", entity=Entity("dimensionless"), uri=Dimensionless_quantity)")]
```

**Comment by nielstron** [comment]
Thanks for the Issue,

> I need get the output as litre not centimeter or meter

As stated in the README, Quantulum does not provide any kind of unit transformation. Please check out the libraries linked in the README or search on the internet for such uses.

> centilitre(cl) predict as dimensionless

Curious, this should not happen. I'll have a look :)
