### ISSUE TITLE
Inverse order ranged Numbers not predicted

### ISSUE THREAD

**Issue by ManivannanIkomet** [nielstron/quantulum3#146]
Hi @nielstron,
If the range exceeds the specified numerical in the library,  then the prediction will be exact otherwise it's not predicted.

**Correct Prediction**
```
parser.parse('20 – 21')
[Quantity(20.5, "Unit(name="dimensionless", entity=Entity("dimensionless"), uri=Dimensionless_quantity)")]
```

**No Prediction**
```
parser.parse('20 – 19')
[]
```

**Comment by ManivannanIkomet** [comment]
Any one please help me.

**Comment by nielstron** [comment]
Hi thanks for this issue!
Which text did you find this example from? The package is intended to parse text written by humans and thus makes the assumption that ranges are (as conventional) noted in an increasing fashion to decrease wrong positives. Hence it would be interesting to see if there are cases where this convention does not apply.
