### ISSUE TITLE
Wrong Prediction

### ISSUE THREAD

**Issue by ManivannanIkomet** [nielstron/quantulum3#147]
**a axy** is predicted unit name as year
```
parser.parse('a axy')
```
OUTPUT:
```
[Quantity(1, "Unit(name="year year", entity=Entity("unknown"), uri=None)")]
```

**Comment by nielstron** [comment]
Hello, thanks for your issue!
Please refer to #127 as to why this happens.

**Comment by ManivannanIkomet** [comment]
Thanks for your response.
Please response this issue #146
