### ISSUE TITLE
Fails with idioms

### ISSUE THREAD

**Issue by Code-ReaQtor** [nielstron/quantulum3#19]
**Describe the bug**
Incorrectly detects measurements from statements with idioms

**To Reproduce**
```python
>>> from quantulum3 import parser
>>> parser.parse("There's even a ton of comments saying the Shield is now heel?")
[Quantity(1, "short ton")]
```

**Expected behavior**
Will not detect anything

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Code-ReaQtor** [comment]
@nielstron 

Would you recommend a way to detect if the sentence contains an idiom? I found a paper somewhere but there's not enough references included.

**Comment by nielstron** [comment]
Maybe also use a classifier for this? 
Otherwise I don't quite see why it would be relevant to check for idioms at all. Be aware that this is quite a complex subject. The benefits don't seem to outweigh the work for this (in my humble opinion).

**Comment by Code-ReaQtor** [comment]
Thanks @nielstron
