### ISSUE TITLE
Cannot parse kV 

### ISSUE THREAD

**Issue by mechanicpanic** [nielstron/quantulum3#190]
**Describe the bug**
I don't know what I'm doing wrong, but quantulum3 always gives "kibibyte volt", "kilogram volt" or even "kelvin volt" for kV for me.
**Expected behavior**
I expect to see "kilovolt", of course.

**Screenshots**
![image](https://user-images.githubusercontent.com/13109900/130938791-695e1e6a-15ea-48ac-80f2-3b5ce1b8b840.png)

**Additional information:**
 - Python Version: 3.8
 - Classifier activated/ sklearn installed: yes
 - OS: Win 10
 - Version 

**Additional context**
I run the pip version and the github version in a Jupyter Notebook...?

**Comment by nielstron** [comment]
It should work with the dev branch,  as of this commit: https://github.com/nielstron/quantulum3/commit/7f30c3df97a04021c012750fc7f0934547a69767

**Comment by nielstron** [comment]
This should be fixed as of version 0.7.8
