### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy.sparse._csr'

### ISSUE THREAD

**Issue by ParimalaS27** [nielstron/quantulum3#196]
**Bug Title**
ModuleNotFoundError: No module named 'scipy.sparse._csr'
The quantulum3 library throws up the above mentioned error, on few input texts. 

**To Reproduce**
1. Import the library
2. Define the input text as : text = "Dawn had some Bread. He cut each Bread into 7 slices. If total 76 Bread slices Dawn make, then how many Bread Dawn had?"
3. Call the parser.parse() function
4. It does not output the numeric entities found for some reason. Instead it throws the error saying "scipy.sparse._csr" module is not found.

**Screenshots**
![image](https://user-images.githubusercontent.com/64643184/191567375-8fe66fb0-88fd-41ce-a5d6-6df00db92809.png)

**Comment by ajosegun** [comment]
Training the classifier worked for me.

from quantulum3 import parser, load, classifier
classifier.train_classifier()

**Comment by ParimalaS27** [comment]
Does that mean that the classifier has to be trained again on the entire data that we're working with?

**Comment by nielstron** [comment]
I guess there has been a change in the underlying scikit package. Try using an older version of the package

**Comment by sutris** [comment]
Had similar issue and it is due to `scipy` was pinned to an older version that don't have `scipy.sparse._csr` (e.g. `scipy==1.7.3`)

Upgrading to `scipy==1.10.1` fix the issue
