### ISSUE TITLE
Does not support numeric abbreviation

### ISSUE THREAD

**Issue by Code-ReaQtor** [nielstron/quantulum3#20]
**Is your feature request related to a problem? Please describe.**
`parser.parse` cannot properly parse numeric abbreviations
```python
>>> parser.parse("1k miles")
[Quantity(1, "unk mile")]
>>> parser.parse("1K miles")
[Quantity(1, "kelvin mile")]
>>> parser.parse("1M miles")
[Quantity(1, "metre mile")]
```

**Describe the solution you'd like**
Should be able to parse numeric abbreviations properly:

> In English numeric abbreviations and currency:
>     K for thousand (from kilo)
>     M for million
>     B for billion
>     T for trillion
> 
> In metric prefixes for SI measurements:
>     k for thousand (note lowercase)
>     M for million (from mega)
>     G for billion (from giga)
>     T for trillion (from tera)

Reference: https://english.stackexchange.com/a/112250

**Comment by nielstron** [comment]
Good point! This is about to come. I'm working on this and composite units in branch `fix-combined-units`

**Comment by nielstron** [comment]
Fixed by #21. Please have a look into it, if it behaves as expected.

**Comment by Code-ReaQtor** [comment]
Hi @nielstron 

It works on my end now. When are you going to release it on PyPI? I see that you've added `scipy` into it. Will it be using `scipy` heavily?

**Comment by Code-ReaQtor** [comment]
Thanks @nielstron 

Cheers! 👍
