### ISSUE TITLE
The parser elaborates quantities with symbols in them

### ISSUE THREAD

**Issue by amontoli** [nielstron/quantulum3#239]
**Describe the bug**
The output of the parser is not the one expected: it extracts numbers that are not present in the text, probably by elaborating calculations inside the text.

**To Reproduce**
Just by using the example in the README:
```
>>> from quantulum3 import parser
>>> parser.parse("The LHC smashes proton beams at 12.8–13.0 TeV")
[Quantity(12.9, "Unit(name="teraelectronvolt", entity=Entity("energy"), uri=Electronvolt)")]
```
Looks like the parser is trying to calculate `12.8 - 13.0` as if it were a subtraction (modulo the sign).

**Expected behavior**
The one present on the README:
```
>>> parser.parse('The LHC smashes proton beams at 12.8–13.0 TeV')
[Quantity(12.8, "teraelectronvolt"), Quantity(13, "teraelectronvolt")]
```
**Additional information:**
 - Python Version: 3.10.14
 - Classifier activated/ sklearn installed: yes
 
**Additional context**
Looks like it is the same also for other signs, like the slash, but in this case it is understandable, as it may confound the slash as if it were a fraction.
```
>>> parser.parse("I'd like 3/4 apples.")
[Quantity(0.75, "Unit(name="dimensionless", entity=Entity("dimensionless"), uri=Dimensionless_quantity)")]
```

**Comment by nielstron** [comment]
This behaviour is expected. The value in the text is a range (between 12.8 and 13.0 TeV, i.e. 12.9+-0.1). Quantulum returns this mean value and the uncertainty extracted (though the latter is appearently not printed)
