### ISSUE TITLE
List Index Out Of Range

### ISSUE THREAD

**Issue by twentytwokhz** [nielstron/quantulum3#41]
**Describe the bug**
parser.parse() on some texts generates this error

**To Reproduce**
1. parser.parse('Acme Inc. re- commenced production at Goondicum in April 2015  but production was paused in August 2015.')
2. See error

**Additional information:**
 - Python Version: 3.6.6
 - Classifier activated/ sklearn installed: [yes/no]
 - OS: Windows 10
 - Version

**Comment by twentytwokhz** [comment]
other cases:
- 'exports decreased from 816 000 t valued at $1943 million  in 2012–13 to 934 000 t valued at $1964 million in 2013–14  and 885 000 t valued at $1854 million in 2014–15.'
- 'in 2012–13 to 279 t valued at $13 009 million in 2013–14  and 278 t valued at $13 049 million in 2014–15.'

**Comment by nielstron** [comment]
The examples Don't produce errors on my device. Yet there are some erroneous outputs:

```
>>> from quantulum3 import parser
>>> parser.parse("exports decreased from 816 000 t valued at $1943 million in 2012–13 to 934 000 t valued at $1964 million in 2013–14 and 885 000 t valued at $1854 million in 2014–15.")
[Quantity(816, "tonne"), Quantity(1.943e+09, "dollar"), Quantity(1012.5, "dimensionless"), Quantity(934, "tonne"), Quantity(1.964e+09, "dollar"), Quantity(1456, "tonne"), Quantity(1.854e+09, "dollar"), Quantity(1014.5, "dimensionless")]
>>> parser.parse("Acme Inc. re- commenced production at Goondicum in April 2015 but production was paused in August 2015.")
[Quantity(2015, "dimensionless"), Quantity(2015, "dimensionless")]
```

- `2012-13` is interpreted as a range. When the second number is less it should be automatically prefixed with other numbers 

- `940 000 t` the three zeroes areas simply ignored, resulting in a wrong magnitude

**Comment by nielstron** [comment]
Moved to #45
