### ISSUE TITLE
Erroneously detected unit is not removed

### ISSUE THREAD

**Issue by nielstron** [nielstron/quantulum3#43]
https://travis-ci.com/nielstron/quantulum3/jobs/143684973#L572

**To Reproduce**
`setup.py test`

**Expected behavior**
See test result

**Comment by nielstron** [comment]
@stephengaw In your pull request, wiki.json was considerably changed. It now contains only 177 instead of 379 LOC. Could you rerun setup.py or simply reconstruct the old wiki.json to check if this fixes the problem. Don't see how any other changed line could have caused the failing build.

**Comment by stephengaw** [comment]
Issue seems to arise from changes to the `clf.pickle` file that was created when the tests were run locally and reproduced the files. Reverting both  `clf.pickle` and `wiki.json` (also changed after local tests)... New PR to follow.

Think it would be worth modifying the unit test `test_training` to undo or not persist changes to files in the course of them running. Currently, this is running the `classifier.train_classifier()` function with no actual checks or validation on output.

**Comment by nielstron** [comment]
Good point

They are currently run to check whether the training can be completed without errors.
Could you comment out the respective tests in your latest PR?

**Comment by nielstron** [comment]
Closed by #44
