### ISSUE TITLE
Languages support! or guidelines for this.

### ISSUE THREAD

**Issue by softmarshmallow** [nielstron/quantulum3#55]
It would be cool to have a sub project for supporting multiple languages.!
would love to know how to add multiple language support (in structure level).

**Comment by nielstron** [comment]
Thanks for the idea! This is roughly working on english texts, though let me ponder a bit about what would be the best way to implement multiple language support. For now, language specific quirks are all over the project, even inside parsing methods, so it won't be easy!

**Comment by nielstron** [comment]
I created a branch for this, [`language_support`](https://github.com/nielstron/quantulum3/tree/language_support). Check it out if you want to implement support for a new language.

If there are any problems please contact me.
